source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '10.20.0'
  pod 'Firebase/AppCheck', '10.20.0'
  pod 'Firebase/Auth', '10.20.0'
  # pod 'Firebase/Core', '10.10.0'
  pod 'Firebase/DynamicLinks', '10.20.0'
  # pod 'GTMSessionFetcher/Core','>=2.1'
  pod 'GoogleSignIn', '7.0.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
